#!/home/tibi/tools/bin/python


import requests
import os


def resolve(links):
    links = links.split()

    fixed = []
    for url in links:

        url = url.replace('http://', 'https://')
        print "Fixing", url
        resp = requests.head(url)
        if 'Location' not in resp.headers:
            fixed.append(url)
            continue

        res = resp.headers['Location']
        fixed.append(res)

    line = 'text=' + ' '.join(fixed) + '\n'
    return line


def fix(fname):
    with open(fname, 'a+') as f:
        lines = []

        for line in f.readlines():
            if line.startswith('text='):
                links = line.split('=')[1]
                line = resolve(links)
            lines.append(line)
        f.seek(0)
        f.truncate()
        content = "".join(lines)
        # print content
        f.write(content)


def main():
    for fname in os.listdir('.'):
        if 'crawljob' not in fname:
            continue
        fix(fname)


if __name__ == "__main__":
    main()
