#!/home/tibi/tools/bin/python
import requests
import os


def resolve(url):
    url = url.replace('http://', 'https://')
    print "Fixing", url
    resp = requests.head(url)
    res = resp.headers['Location']
    return res

def fix(fname):
    """ Fixes the links from the lines that start with text= """

    with open(fname, 'a+') as f:
        lines = []
        fixed = []
        for line in f.readlines():
            if line.startswith('text='):
                # sol 1
                links = line.split('=')[1].split()
                for url in links:
                    resolved_url = resolve(url)
                    fixed.append(resolved_url)
                    print ' '.join(fixed)
                    line = 'text=' + ' '.join(fixed) + '\n'

                # sol 2
                fixed += [resolve(url) for url in line.split('=')[1].split()]
                print ' '.join(fixed)
                line = 'text=' + ' '.join(fixed) + '\n'
                # append line to lines
                lines.append(line)
        f.seek(0)
        f.truncate()
        content = "".join(lines)
        # print content
        f.write(content)


def main():
    for fname in os.listdir('.'):
        if 'crawljob' not in fname:
            continue
        fix(fname)


if __name__ == "__main__":
    main()
