#!/home/tibi/tools/bin/python


import requests
import os


def resolve(url):
    # for url in urls:
    url = url.replace('http://', 'https://')
    print "Fixing", url
    resp = requests.head(url)
    res = resp.headers['Location']
    return res

def fix(fname):
    # import pdb; pdb.set_trace()
    with open(fname, 'a+') as f:
        lines = []
        fixed = []
        for line in f.readlines():
            if line.startswith('text='):
                links = line.split('=')[1]
                link = links.split()
                for url in link:
                    resolved_link = resolve(url)
                    fixed.append(url)
                    print ' '.join(fixed)
                    # print ' '.join(fixed)
                    line = 'text=' + ' '.join(fixed) + '\n'

            lines.append(line)
        f.seek(0)
        f.truncate()
        content = "".join(lines)
        # print content
        f.write(content)


def main():
    for fname in os.listdir('.'):
        if 'crawljob' not in fname:
            continue
        fix(fname)


if __name__ == "__main__":
    main()
